### ISSUE TITLE
Links setup

### ISSUE THREAD

**Issue by indigotec** [mostafa272/TableMakerforCSV#12]
Hi Mostafa272, first congratulation, the plugin works well for now (beta article: http://www.indigotec.cl/academia). At the beginning was a little hard to setup, but after some intends it goes Ok. I'm stuck with the links setup, as you post the plugin accepts those links I want to test them, could you send an example how the Excel (or .csv) should be filled?

Where can I change the "Search for" from english to spanish" (I'm not a developer, but understand a lot of your world)

![TableCSV](https://user-images.githubusercontent.com/79864429/109534892-9cd9be00-7a9a-11eb-9d3e-b58bc36122b1.jpg)

That for now, thanks

**Mauricio Dabdoub**

**Comment by indigotec** [comment]
I'm stuck with the links setup, how do we configure them, could you show an example how the Excel (or .csv) should be filled? and the final table how it looks online? the link should not be an extra column.

**Comment by AlainRnet** [comment]
You can change "Search for" in default.php on line ~58, the best is to do an override in your template.

**Comment by AlainRnet** [comment]
For links, do you mean links in your file ? I did it in a private file (sorry, no link to publish here), I write HTML in the CSV file. I hope this helps you.

**Comment by indigotec** [comment]
thanks

**Comment by indigotec** [comment]
thanks, I moved to joomla 4.26

**Comment by AlainRnet** [comment]
I forgot I posted here. Here is the link that was not accessible at the time of my answer: www.yens.ch/vie-locale/commerces-et-entreprises/liste-des-entreprises
