### ISSUE TITLE
csv with different separator

### ISSUE THREAD

**Issue by NafetsM** [mostafa272/TableMakerforCSV#5]
Hello,
I like your tool. Might it be possible to alter the separoter to ";"? My german Excel is exporting the csv with that seperator, so I would prefer to use this one directly. (As a suggestion a dropdown in the configuration page?)
Best regards,
NafetsM

**Comment by mostafa272** [comment]
If didn't understand your means. You should explain with more details. If you have multiple value in each cell, how do you want to show it in a output HTML table? (Output table structure is not clear)

**Comment by NafetsM** [comment]
Your importer uses a <, > as separator. In my german Excel the standard
separator is <;>. That's common practice here as we use <, > to indicate
the decimal place.

Am Do., 7. Feb. 2019, 18:53 hat Mostafa Shahiri <notifications@github.com>
geschrieben:

**Comment by NafetsM** [comment]
Now I've got a sample csv, exported directly from my Excel:
"
Platz;Team;Spiele;Siege;Niederlagen;Prozent;Runs-For;Runs-Against;Differenz
0;Aschaffenburg Mohawks;0;0;0;#DIV/0!;0;0;0
0;Babenhausen;0;0;0;#DIV/0!;0;0;0
"
You can see, that the separator is different from an english Excel. The individual cells are divided with the semicolon.

**Comment by mostafa272** [comment]
OK, I understood. I read a csv file with fgetcsv function. I did not pass separator element as a input parameter, so it uses default separator (,). To reach what you want:

1) Open default.php file in tmpl folder of this module.
2) Find following code 
`
while($f=fgetcsv($file))
`
Change it to 
`
while($f=fgetcsv( $file , 1000 , ";" ))
`
Save the file. That's it. I think it should work for you.

**Comment by NafetsM** [comment]
Perfect, thanks a lot. That make's it easier for me.
