### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by lemcbl** [mostafa272/TableMakerforCSV#6]
Hello

1. Is it possible to put the search field below the table?

2. I see the search field but I don't see the button to search, so nothing happens...

https://cinnabar.joomla.com/index.php

Great extention btw, much easier to import our excel tables to a new site! thanks!

**Comment by lemcbl** [comment]
Also, is it possible to set up the width of each column?

**Comment by mostafa272** [comment]
@lemcbl Hi, 
searching in the table occurs on writing in search field and there's no need to button.
To change the position of search field:
1. Open default.php file (in tmpl directory) and find following code:
`
 echo '<input type="text" id="csvlookup" onkeyup="lookuptable('.$row_num.')" placeholder="Search for ..."><br/>';  

`
2. Select and cut above code and then paste it after following code (it should be at line 83):
`
echo '</table>';
`
That's it. Now you have search field below the table. 
You should be familiar with CSS to assign width for table cells. You can add your CSS code to default.php file. For example, by following code, you can assign width for first column:
`
.csvtable".$moduleclass_sfx." td:first-child{
width:500px;

}
`
You can put this code somewhere before (line 25)
`
.csvtable".$moduleclass_sfx." tr:nth-child(even) td 
`
 and save the default.php file.

**Comment by lemcbl** [comment]
@mostafa272

Thanks for the reply of both questions. I just don't see the search doing anything....

For instance, in this test website: https://cinnabar.joomla.com/, if you start typing "worst"... should it show only the line that starts with 2006?

Another question: do you plan to add the sort feature by top row field in the future?

Thanks again

**Comment by mostafa272** [comment]
@lemcbl 
I'm so busy in these days and I don't have any plan for developing this module. I think I forgot to add js folder to manifest file. Please download and install following file on your website. Please try it and let me know it works correctly.
[mod_tablemakerforcsv_v2.zip](https://github.com/mostafa272/TableMakerforCSV/files/2895104/mod_tablemakerforcsv_v2.zip)

**Comment by lemcbl** [comment]
@mostafa272 thanks for your answer. It works now. Just one more question, can I keep the search on top of the table but aligned to the right?

**Comment by mostafa272** [comment]
@lemcbl 
You can add CSS code to default.php file similar to same way that I explained in previous replies.
 
Use following code to change search field alignment:                           
                  
`#csvlookup {
float: right;
}`
You can put this code somewhere before line 36 (before #csvpagination a{ )

`.csvtable".$moduleclass_sfx." tr:nth-child(even) td `

and save the default.php fil

**Comment by lemcbl** [comment]
Thank you again, works great
