### ISSUE TITLE
Character set

### ISSUE THREAD

**Issue by mderouge** [mostafa272/TableMakerforCSV#9]
Hi Mostafa,
The module is simple and great. Yet there is one issue: the content of my table contains latin characters such as é.ü,â that are disappearing in the table view.
How to define a correct character set? for example UTF-8

**Comment by mostafa272** [comment]
Open default.php file in tmpl folder. At lines 70 , 71 there are commented codes:
//setlocale(LC_ALL, 'UTF-8');
//mb_internal_encoding('UTF-8');
 Remove // from these lines and save the file. Test module again. I hope it solves the problem.

**Comment by mderouge** [comment]
Thank you Mostafa, you almost made may day!
Almost, because it was necessary to suppress also the // on line 77
//$f = array_map("utf8_encode", $f);
